### ISSUE TITLE
`v8age` has non-numeric values

### ISSUE THREAD

**Issue by remomueller** [sleepepi/sof-data-dictionary#35]
Reported by Matthew Butler here: https://sleepdata.org/forum/54-sof-ages-of-g-or-h-variable-v8age

**Comment by mrueschman** [comment]
SAS missing codes for extreme low and high values. 

![sof_age_format](https://cloud.githubusercontent.com/assets/707167/12659089/e3fea838-c5da-11e5-9801-1a04426a9048.png)

**Comment by mrueschman** [comment]
Closed in 0.4.0 by recoding missing to null. (Spout issue could still be useful to undertake.)
